runtime: custom
env: flex
entrypoint: streamlit run app.py --server.port=$PORT --server.address=0.0.0.0

resources:
  cpu: 1
  memory_gb: 1
  disk_size_gb: 10

env_variables:
  BUCKET_NAME: "videos_y_audios"

runtime_config:
  python_version: 3.10
